### ISSUE TITLE
Allow parametrize headers/body

### ISSUE THREAD

**Issue by gabheadz** [bancolombia/distributed-performance-analyzer#23]
Some scenarios requiere headers data and/or body payload to mutate on each request. It would be nice to use some faking lib (e.g [Faker](https://github.com/elixirs/faker)) to introduce fake data in each request. 

A basic approach could be:

1. Defining placeholders to indicate where random data is to be generated/inserted, in the request config.

```elixir
request: %{method: "POST", headers: [{"Content-Type", "application/json"}], body: "{\"name\": \"#Fake.Person.Name#\"}"}
```

2. Generating random data

```elixir
defmodule Perf.LoadGenerator do
 [...]
  defp request(%Request{method: method, path: path, headers: headers, body: body, url: url}, conn) do
    {total_time, result} = try do
      # proposed change
      mutated_body = generateRandomDataAndReplacePlaceholders(body)
      Perf.ConnectionProcess.request(conn, method, path, headers, mutated_body)
    catch
      _, error -> {0, :invocation_error}
    end
  end
end
```

**Comment by gabheadz** [comment]
I realized this would be a duplicate of #13

**Comment by JuanDGiraldoM** [comment]
Hi @gabheadz 

Now you can use datasets or inlude Enum.random at the body section

#27
